@id = c76a35da-b48e-4368-806c-20e8ce8f8346

PUT http://localhost:5048/vacations/{{id}}
Content-Type: application/json

{
    "title": "Steamy London",
    "description": "Following Train Tracks: Von Bristol nach Manchester!",
    "startDate": "2025-04-08",
    "endDate": "2025-04-22",
    "length": "14",
    "price": "222200"
}